# src/main/resources/application-prod.properties
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
logging.level.root=WARN
logging.level.com.universidad=INFO

springdoc.api-docs.enabled=false
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
